AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2010-09-09'
Description: A starter AWS Lambda function.
Parameters: 
    IdentityNameParameter: 
      Type: String
Resources:
  machineinfo:
    Type: 'AWS::Serverless::Function'
    Properties:
      Runtime: python3.7
      CodeUri: .
      Description: A starter AWS Lambda function.
      MemorySize: 128
      Timeout: 3
