apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-cloud-machineinfo
  namespace: dev
spec:
  selector:
    matchLabels:
      app: machineinfo
  replicas: 1
  template:
    metadata:
      labels:
        app: machineinfo      
    spec:
      containers:
      - name: machineinfo
        image: nehashirsat/machineinfo:v1
        securityContext:
          allowPrivilegeEscalation: false
        imagePullPolicy: Always
        ports:
        - containerPort: 9000
        volumeMounts:
        - mountPath: /volume
          name: machineinfo-volume
      volumes:
      - name: machineinfo-volume
        hostPath:
          path: /var/tmp/volume
          type: DirectoryOrCreate
