apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-cloud-machineinfo
spec:
  selector:
    matchLabels:
      app: machineinfo
  replicas: 1
  template:
    metadata:
      labels:
        app: machineinfo
    spec:
      containers:
      - image: nehashirsat/machineinfo:v1
        name: machineinfo
        ports:
        - containerPort: 9000
        env:
        - name: myusername
          valueFrom:
            secretKeyRef:
              name: mysqlcredentials
              key: username
