apiVersion: v1
kind: Service
metadata:
  name: devops-cloud-machineinfo
  labels:
    app: machineinfo
  namespace: dev
spec:
  selector:
    app: machineinfo
  type: NodePort
  ports:
  - nodePort: 31000
    port: 9000
    targetPort: 9000
